---
title: "Perinatal Diet and Preeclampsia: Interactive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(here)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)
library(htmltools)
library(reactable)

source(here("scripts", "lasso.R"))
source(here("scripts", "all_results.R"))
```

# Project Overview
=====================================

Row
-------------------------------------

### Dataset Description & Project Information
```{r}
HTML("
<div style='background-color:white; padding:15px; border-radius:8px; border:1px solid #e0e0e0;'>

<b>Dataset Description</b><br>
This study uses data from a large prospective cohort of nulliparous pregnant individuals in the United States. The dataset is not publicly available and is considered confidential.<br><br>

Dietary intake was collected during early pregnancy using a food frequency questionnaire and summarized into food group variables. Additional demographic and clinical information was collected through standardized study visits and questionnaires.<br><br>

The analytic sample includes over 8,000 participants enrolled between 2010 and 2013 across multiple clinical sites.<br><br>

<b>Real-World Impact</b><br>
This dashboard shows that results about diet and preeclampsia can change depending on the clustering method used. This highlights the need for careful methodological choices in nutritional epidemiology and more cautious interpretation of findings.<br><br>

<b>Project Repository</b><br>
View the full project code here: 
<a href='https://github.com/cdiazbe/DATA555_Dashboard' target='_blank'>
https://github.com/cdiazbe/DATA555_Dashboard
</a><br><br>

</div>
")
```

# Clustering Variability in Dietary Patterns
=====================================

Column {.tabset}
-------------------------------------

### K-means
```{r}
tagList(
  div(style = "height:450px;",
      ggplotly(p1, tooltip = "text")
  ),
  
  div(
    style = "font-size:14px; line-height:1.5; margin-top:10px;",
    HTML("
<b>Summary</b><br>
    K-means identified clusters characterized by sweetened beverages, sweet bakery products, and white potatoes in cluster 1, and by vegetables (excluding potatoes), coffee and tea, and fruits in cluster 2.")
))
```

### K-medoids
```{r}
tagList(
  div(style = "height:450px;",
      ggplotly(p2, tooltip = "text")
  ),
  
  div(
    style = "font-size:14px; line-height:1.5; margin-top:10px;",
    HTML("
<b>Summary</b><br>
    K-medoids characterized cluster 1 by ready-to-eat cereal, crackers, and candy, and cluster 2 by alcoholic beverages, coffee and tea, and yogurt.")
))
```

### Hierarchical
```{r}
tagList(
  div(style = "height:450px;",
      ggplotly(p3, tooltip = "text")
  ),
  
  div(
    style = "font-size:14px; line-height:1.5; margin-top:10px;",
    HTML("
<b>Summary</b><br>
    For Hierarchical clustering, vegetables (excluding potatoes), coffee and tea, and diet beverages characterized cluster 1, whereas sweetened beverages, savory snacks, and pizza defined cluster 2.")
))
```

### GMM
```{r}
tagList(
  div(style = "height:450px;",
      ggplotly(p4, tooltip = "text")
  ),
  
  div(
    style = "font-size:14px; line-height:1.5; margin-top:10px;",
    HTML("
<b>Summary</b><br>
    In Gaussian Mixture Modelling, cluster 1 showed particularly elevated log-odds for sweetened beverages, 100% juice, and alcoholic beverages, while cluster 2's highest values were for diet beverages, beans/vegetables, and coffee and tea.")
))
```

# Perinatal Diet and Preeclampsia Risk
=====================================
Row {data-height=1}
-------------------------------------

```{r}
HTML("<h3>Risk Difference for Preeclampsia per <b>100 pregnancies</b></h3>")
```

Row {data-height=6}
-------------------------------------
```{r}
tagList(
  div(style = "height:450px;",
      ggplotly(p, tooltip = "text")
  ),
  
  div(
    style = "background-color:white; 
            padding:12px; 
            border-radius:8px;
            font-size:14px; 
            line-height:1.6; 
            margin-top:10px;
            border: 1px solid #e0e0e0;",
))
```
Row {data-height=2}
-------------------------------------

```{r}
HTML("
<b>Summary</b><br>
K-means showed a lower risk of preeclampsia, while Hierarchical clustering showed a higher risk. K-medoids and GMM showed minimal differences. All confidence intervals included the null, suggesting no statistically significant associations.
")
```
